export type ModuleId =
  | 'background'
  | 'timer'
  | 'turntaking'
  | 'groups'
  | 'instructioncards'
  | 'trafficlight'
  | 'randomizer'
  | 'clock'
  | 'seating'
  | 'lessonplan'
  | 'exitticket'
  | 'soundmeter'
